FROM bitnami/spark:latest

# Install psycopg2
USER root
RUN apt-get update && \
    apt-get install -y python3-pip && \
    pip3 install psycopg2-binary

# Switch back to the non-root Spark user
USER 1001