version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: transakcije
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rea123Teo
    ports:
      - "5433:5432"

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    depends_on:
      - postgres
